/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTabelasRouteImport } from './routes/_app.tabelas'
import { Route as AppSincronizacaoRouteImport } from './routes/_app.sincronizacao'
import { Route as AppQueriesRouteImport } from './routes/_app.queries'
import { Route as AppEmpresasRouteImport } from './routes/_app.empresas'
import { Route as AppConfiguracoesRouteImport } from './routes/_app.configuracoes'
import { Route as AppConectividadeRouteImport } from './routes/_app.conectividade'
import { Route as AppBancosRouteImport } from './routes/_app.bancos'
import { Route as AppAgenteRouteImport } from './routes/_app.agente'
import { Route as AppAcessosRouteImport } from './routes/_app.acessos'
import { Route as ApiPublicSyncRouteImport } from './routes/api/public/sync'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'
import { Route as ApiPublicLogsRouteImport } from './routes/api/public/logs'
import { Route as ApiPublicHeartbeatRouteImport } from './routes/api/public/heartbeat'
import { Route as ApiPublicCommand_resultRouteImport } from './routes/api/public/command_result'
import { Route as ApiPublicAgentVersionRouteImport } from './routes/api/public/agent-version'
import { Route as ApiPublicAgentReportRouteImport } from './routes/api/public/agent-report'
import { Route as ApiPublicAgentProbeRouteImport } from './routes/api/public/agent-probe'
import { Route as ApiPublicAgentInstallerRouteImport } from './routes/api/public/agent-installer'
import { Route as ApiPublicAgentDownloadRouteImport } from './routes/api/public/agent-download'
import { Route as ApiPublicAgentBundleRouteImport } from './routes/api/public/agent-bundle'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTabelasRoute = AppTabelasRouteImport.update({
  id: '/tabelas',
  path: '/tabelas',
  getParentRoute: () => AppRoute,
} as any)
const AppSincronizacaoRoute = AppSincronizacaoRouteImport.update({
  id: '/sincronizacao',
  path: '/sincronizacao',
  getParentRoute: () => AppRoute,
} as any)
const AppQueriesRoute = AppQueriesRouteImport.update({
  id: '/queries',
  path: '/queries',
  getParentRoute: () => AppRoute,
} as any)
const AppEmpresasRoute = AppEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppConectividadeRoute = AppConectividadeRouteImport.update({
  id: '/conectividade',
  path: '/conectividade',
  getParentRoute: () => AppRoute,
} as any)
const AppBancosRoute = AppBancosRouteImport.update({
  id: '/bancos',
  path: '/bancos',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteRoute = AppAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AppRoute,
} as any)
const AppAcessosRoute = AppAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicSyncRoute = ApiPublicSyncRouteImport.update({
  id: '/api/public/sync',
  path: '/api/public/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({
  id: '/api/public/register',
  path: '/api/public/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLogsRoute = ApiPublicLogsRouteImport.update({
  id: '/api/public/logs',
  path: '/api/public/logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHeartbeatRoute = ApiPublicHeartbeatRouteImport.update({
  id: '/api/public/heartbeat',
  path: '/api/public/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCommand_resultRoute = ApiPublicCommand_resultRouteImport.update({
  id: '/api/public/command_result',
  path: '/api/public/command_result',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentVersionRoute = ApiPublicAgentVersionRouteImport.update({
  id: '/api/public/agent-version',
  path: '/api/public/agent-version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentReportRoute = ApiPublicAgentReportRouteImport.update({
  id: '/api/public/agent-report',
  path: '/api/public/agent-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentProbeRoute = ApiPublicAgentProbeRouteImport.update({
  id: '/api/public/agent-probe',
  path: '/api/public/agent-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentInstallerRoute = ApiPublicAgentInstallerRouteImport.update({
  id: '/api/public/agent-installer',
  path: '/api/public/agent-installer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentDownloadRoute = ApiPublicAgentDownloadRouteImport.update({
  id: '/api/public/agent-download',
  path: '/api/public/agent-download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentBundleRoute = ApiPublicAgentBundleRouteImport.update({
  id: '/api/public/agent-bundle',
  path: '/api/public/agent-bundle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/acessos': typeof AppAcessosRoute
  '/agente': typeof AppAgenteRoute
  '/bancos': typeof AppBancosRoute
  '/conectividade': typeof AppConectividadeRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/empresas': typeof AppEmpresasRoute
  '/queries': typeof AppQueriesRoute
  '/sincronizacao': typeof AppSincronizacaoRoute
  '/tabelas': typeof AppTabelasRoute
  '/api/public/agent-bundle': typeof ApiPublicAgentBundleRoute
  '/api/public/agent-download': typeof ApiPublicAgentDownloadRoute
  '/api/public/agent-installer': typeof ApiPublicAgentInstallerRoute
  '/api/public/agent-probe': typeof ApiPublicAgentProbeRoute
  '/api/public/agent-report': typeof ApiPublicAgentReportRoute
  '/api/public/agent-version': typeof ApiPublicAgentVersionRoute
  '/api/public/command_result': typeof ApiPublicCommand_resultRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/api/public/logs': typeof ApiPublicLogsRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/acessos': typeof AppAcessosRoute
  '/agente': typeof AppAgenteRoute
  '/bancos': typeof AppBancosRoute
  '/conectividade': typeof AppConectividadeRoute
  '/configuracoes': typeof AppConfiguracoesRoute
  '/empresas': typeof AppEmpresasRoute
  '/queries': typeof AppQueriesRoute
  '/sincronizacao': typeof AppSincronizacaoRoute
  '/tabelas': typeof AppTabelasRoute
  '/': typeof AppIndexRoute
  '/api/public/agent-bundle': typeof ApiPublicAgentBundleRoute
  '/api/public/agent-download': typeof ApiPublicAgentDownloadRoute
  '/api/public/agent-installer': typeof ApiPublicAgentInstallerRoute
  '/api/public/agent-probe': typeof ApiPublicAgentProbeRoute
  '/api/public/agent-report': typeof ApiPublicAgentReportRoute
  '/api/public/agent-version': typeof ApiPublicAgentVersionRoute
  '/api/public/command_result': typeof ApiPublicCommand_resultRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/api/public/logs': typeof ApiPublicLogsRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/acessos': typeof AppAcessosRoute
  '/_app/agente': typeof AppAgenteRoute
  '/_app/bancos': typeof AppBancosRoute
  '/_app/conectividade': typeof AppConectividadeRoute
  '/_app/configuracoes': typeof AppConfiguracoesRoute
  '/_app/empresas': typeof AppEmpresasRoute
  '/_app/queries': typeof AppQueriesRoute
  '/_app/sincronizacao': typeof AppSincronizacaoRoute
  '/_app/tabelas': typeof AppTabelasRoute
  '/_app/': typeof AppIndexRoute
  '/api/public/agent-bundle': typeof ApiPublicAgentBundleRoute
  '/api/public/agent-download': typeof ApiPublicAgentDownloadRoute
  '/api/public/agent-installer': typeof ApiPublicAgentInstallerRoute
  '/api/public/agent-probe': typeof ApiPublicAgentProbeRoute
  '/api/public/agent-report': typeof ApiPublicAgentReportRoute
  '/api/public/agent-version': typeof ApiPublicAgentVersionRoute
  '/api/public/command_result': typeof ApiPublicCommand_resultRoute
  '/api/public/heartbeat': typeof ApiPublicHeartbeatRoute
  '/api/public/logs': typeof ApiPublicLogsRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
  '/api/public/sync': typeof ApiPublicSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/acessos'
    | '/agente'
    | '/bancos'
    | '/conectividade'
    | '/configuracoes'
    | '/empresas'
    | '/queries'
    | '/sincronizacao'
    | '/tabelas'
    | '/api/public/agent-bundle'
    | '/api/public/agent-download'
    | '/api/public/agent-installer'
    | '/api/public/agent-probe'
    | '/api/public/agent-report'
    | '/api/public/agent-version'
    | '/api/public/command_result'
    | '/api/public/heartbeat'
    | '/api/public/logs'
    | '/api/public/register'
    | '/api/public/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/acessos'
    | '/agente'
    | '/bancos'
    | '/conectividade'
    | '/configuracoes'
    | '/empresas'
    | '/queries'
    | '/sincronizacao'
    | '/tabelas'
    | '/'
    | '/api/public/agent-bundle'
    | '/api/public/agent-download'
    | '/api/public/agent-installer'
    | '/api/public/agent-probe'
    | '/api/public/agent-report'
    | '/api/public/agent-version'
    | '/api/public/command_result'
    | '/api/public/heartbeat'
    | '/api/public/logs'
    | '/api/public/register'
    | '/api/public/sync'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/acessos'
    | '/_app/agente'
    | '/_app/bancos'
    | '/_app/conectividade'
    | '/_app/configuracoes'
    | '/_app/empresas'
    | '/_app/queries'
    | '/_app/sincronizacao'
    | '/_app/tabelas'
    | '/_app/'
    | '/api/public/agent-bundle'
    | '/api/public/agent-download'
    | '/api/public/agent-installer'
    | '/api/public/agent-probe'
    | '/api/public/agent-report'
    | '/api/public/agent-version'
    | '/api/public/command_result'
    | '/api/public/heartbeat'
    | '/api/public/logs'
    | '/api/public/register'
    | '/api/public/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiPublicAgentBundleRoute: typeof ApiPublicAgentBundleRoute
  ApiPublicAgentDownloadRoute: typeof ApiPublicAgentDownloadRoute
  ApiPublicAgentInstallerRoute: typeof ApiPublicAgentInstallerRoute
  ApiPublicAgentProbeRoute: typeof ApiPublicAgentProbeRoute
  ApiPublicAgentReportRoute: typeof ApiPublicAgentReportRoute
  ApiPublicAgentVersionRoute: typeof ApiPublicAgentVersionRoute
  ApiPublicCommand_resultRoute: typeof ApiPublicCommand_resultRoute
  ApiPublicHeartbeatRoute: typeof ApiPublicHeartbeatRoute
  ApiPublicLogsRoute: typeof ApiPublicLogsRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
  ApiPublicSyncRoute: typeof ApiPublicSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tabelas': {
      id: '/_app/tabelas'
      path: '/tabelas'
      fullPath: '/tabelas'
      preLoaderRoute: typeof AppTabelasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sincronizacao': {
      id: '/_app/sincronizacao'
      path: '/sincronizacao'
      fullPath: '/sincronizacao'
      preLoaderRoute: typeof AppSincronizacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/queries': {
      id: '/_app/queries'
      path: '/queries'
      fullPath: '/queries'
      preLoaderRoute: typeof AppQueriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/empresas': {
      id: '/_app/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AppEmpresasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracoes': {
      id: '/_app/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/conectividade': {
      id: '/_app/conectividade'
      path: '/conectividade'
      fullPath: '/conectividade'
      preLoaderRoute: typeof AppConectividadeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bancos': {
      id: '/_app/bancos'
      path: '/bancos'
      fullPath: '/bancos'
      preLoaderRoute: typeof AppBancosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agente': {
      id: '/_app/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AppAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/acessos': {
      id: '/_app/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AppAcessosRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/sync': {
      id: '/api/public/sync'
      path: '/api/public/sync'
      fullPath: '/api/public/sync'
      preLoaderRoute: typeof ApiPublicSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register': {
      id: '/api/public/register'
      path: '/api/public/register'
      fullPath: '/api/public/register'
      preLoaderRoute: typeof ApiPublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/logs': {
      id: '/api/public/logs'
      path: '/api/public/logs'
      fullPath: '/api/public/logs'
      preLoaderRoute: typeof ApiPublicLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/heartbeat': {
      id: '/api/public/heartbeat'
      path: '/api/public/heartbeat'
      fullPath: '/api/public/heartbeat'
      preLoaderRoute: typeof ApiPublicHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/command_result': {
      id: '/api/public/command_result'
      path: '/api/public/command_result'
      fullPath: '/api/public/command_result'
      preLoaderRoute: typeof ApiPublicCommand_resultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-version': {
      id: '/api/public/agent-version'
      path: '/api/public/agent-version'
      fullPath: '/api/public/agent-version'
      preLoaderRoute: typeof ApiPublicAgentVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-report': {
      id: '/api/public/agent-report'
      path: '/api/public/agent-report'
      fullPath: '/api/public/agent-report'
      preLoaderRoute: typeof ApiPublicAgentReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-probe': {
      id: '/api/public/agent-probe'
      path: '/api/public/agent-probe'
      fullPath: '/api/public/agent-probe'
      preLoaderRoute: typeof ApiPublicAgentProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-installer': {
      id: '/api/public/agent-installer'
      path: '/api/public/agent-installer'
      fullPath: '/api/public/agent-installer'
      preLoaderRoute: typeof ApiPublicAgentInstallerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-download': {
      id: '/api/public/agent-download'
      path: '/api/public/agent-download'
      fullPath: '/api/public/agent-download'
      preLoaderRoute: typeof ApiPublicAgentDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-bundle': {
      id: '/api/public/agent-bundle'
      path: '/api/public/agent-bundle'
      fullPath: '/api/public/agent-bundle'
      preLoaderRoute: typeof ApiPublicAgentBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAcessosRoute: typeof AppAcessosRoute
  AppAgenteRoute: typeof AppAgenteRoute
  AppBancosRoute: typeof AppBancosRoute
  AppConectividadeRoute: typeof AppConectividadeRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppEmpresasRoute: typeof AppEmpresasRoute
  AppQueriesRoute: typeof AppQueriesRoute
  AppSincronizacaoRoute: typeof AppSincronizacaoRoute
  AppTabelasRoute: typeof AppTabelasRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcessosRoute: AppAcessosRoute,
  AppAgenteRoute: AppAgenteRoute,
  AppBancosRoute: AppBancosRoute,
  AppConectividadeRoute: AppConectividadeRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppEmpresasRoute: AppEmpresasRoute,
  AppQueriesRoute: AppQueriesRoute,
  AppSincronizacaoRoute: AppSincronizacaoRoute,
  AppTabelasRoute: AppTabelasRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiPublicAgentBundleRoute: ApiPublicAgentBundleRoute,
  ApiPublicAgentDownloadRoute: ApiPublicAgentDownloadRoute,
  ApiPublicAgentInstallerRoute: ApiPublicAgentInstallerRoute,
  ApiPublicAgentProbeRoute: ApiPublicAgentProbeRoute,
  ApiPublicAgentReportRoute: ApiPublicAgentReportRoute,
  ApiPublicAgentVersionRoute: ApiPublicAgentVersionRoute,
  ApiPublicCommand_resultRoute: ApiPublicCommand_resultRoute,
  ApiPublicHeartbeatRoute: ApiPublicHeartbeatRoute,
  ApiPublicLogsRoute: ApiPublicLogsRoute,
  ApiPublicRegisterRoute: ApiPublicRegisterRoute,
  ApiPublicSyncRoute: ApiPublicSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
